#!/bin/bash
#
#######################################################################
# TRIOS Image writer                                                  #
# Simple dd wrapper.                                                  #
#                                                                     #
# This script actually calls dd.                                      #
#                                                                     #
# 2015 Filip Danilovic <filip@openmailbox.org>                        #
#                                                                     #
# This is free software. Licenced under GPL v2 or later. :)           #
#######################################################################


if (($EUID != 0)); then
  if [[ -t 1 ]]; then
    exec sudo bash "$0" "$@"
  else
    exec gksu bash "$0" "$@"
  fi
  exit
fi

if (($EUID == 0)); then
	(dd if="$1" | pv -n -s "$2" | dd of="$3" bs=4M oflag=dsync) 2>&1 | \
	zenity --title="TRIOS Image writer" --text="$(echo -e "Writing `basename $1`:")" --no-cancel \
			--width=300 --ok-label=Finish --progress
	echo -e "\n "
	echo "Writing \"$1\", size \"$2\" to \"$3\"
	exit
else
	if [[ -t 1 ]]; then
	echo "NOT ROOT"
	else
	zenity --error --text="You are not root"
	fi
exit
fi
